-- PART 4: RIDES TABLE WITH YEAR-BASED PARTITIONING
CREATE TABLE IF NOT EXISTS rides (
    ride_id BIGINT NOT NULL AUTO_INCREMENT,
    external_id CHAR(36) NOT NULL DEFAULT (UUID()),
    user_id BIGINT NOT NULL,
    driver_id BIGINT DEFAULT NULL,
    vehicle_id BIGINT DEFAULT NULL,
    city_id INT NOT NULL,
    pickup_zone_id INT DEFAULT NULL,
    dropoff_zone_id INT DEFAULT NULL,
    status ENUM('requested','accepted','driver_en_route','in_progress','completed','cancelled','disputed') NOT NULL DEFAULT 'requested',
    pickup_lat DECIMAL(10,8) NOT NULL,
    pickup_lon DECIMAL(11,8) NOT NULL,
    pickup_address_encrypted BLOB DEFAULT NULL,
    dropoff_lat DECIMAL(10,8) NOT NULL,
    dropoff_lon DECIMAL(11,8) NOT NULL,
    dropoff_address_encrypted BLOB DEFAULT NULL,
    estimated_distance_km DECIMAL(8,3) DEFAULT NULL,
    actual_distance_km DECIMAL(8,3) DEFAULT NULL,
    estimated_duration_minutes SMALLINT DEFAULT NULL,
    actual_duration_minutes SMALLINT DEFAULT NULL,
    base_fare DECIMAL(10,2) DEFAULT NULL,
    surge_multiplier DECIMAL(4,2) NOT NULL DEFAULT 1.00,
    distance_fare DECIMAL(10,2) DEFAULT NULL,
    time_fare DECIMAL(10,2) DEFAULT NULL,
    total_fare DECIMAL(10,2) DEFAULT NULL,
    driver_earnings DECIMAL(10,2) DEFAULT NULL,
    platform_commission DECIMAL(10,2) DEFAULT NULL,
    payment_method ENUM('cash','telebirr','cbe_birr','awash_pay','amole','card') NOT NULL DEFAULT 'cash',
    requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    accepted_at DATETIME DEFAULT NULL,
    driver_arrived_at DATETIME DEFAULT NULL,
    started_at DATETIME DEFAULT NULL,
    completed_at DATETIME DEFAULT NULL,
    cancelled_at DATETIME DEFAULT NULL,
    cancellation_reason VARCHAR(255) DEFAULT NULL,
    cancelled_by VARCHAR(50) DEFAULT NULL,
    user_rating TINYINT DEFAULT NULL,
    driver_rating TINYINT DEFAULT NULL,
    user_feedback TEXT DEFAULT NULL,
    is_scheduled TINYINT(1) NOT NULL DEFAULT 0,
    scheduled_for DATETIME DEFAULT NULL,
    version INT NOT NULL DEFAULT 1,
    ride_year SMALLINT NOT NULL,
    PRIMARY KEY (ride_id, ride_year),
    UNIQUE KEY uq_ride_external (external_id, ride_year),
    KEY idx_ride_user (user_id, requested_at),
    KEY idx_ride_driver (driver_id, requested_at),
    KEY idx_ride_city (city_id, requested_at),
    KEY idx_ride_status (status),
    KEY idx_ride_pickup (pickup_lat, pickup_lon),
    KEY idx_ride_completed (completed_at),
    CONSTRAINT chk_user_rating CHECK (user_rating BETWEEN 1 AND 5),
    CONSTRAINT chk_driver_rating_val CHECK (driver_rating BETWEEN 1 AND 5),
    CONSTRAINT chk_surge CHECK (surge_multiplier >= 1.00 AND surge_multiplier <= 10.00)
) ENGINE=InnoDB
PARTITION BY RANGE (ride_year) (
    PARTITION p2023 VALUES LESS THAN (2024),
    PARTITION p2024 VALUES LESS THAN (2025),
    PARTITION p2025 VALUES LESS THAN (2026),
    PARTITION p2026 VALUES LESS THAN (2027),
    PARTITION p_future VALUES LESS THAN MAXVALUE
);
