-- PART 2: USER AND PHONE TABLES
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT NOT NULL AUTO_INCREMENT,
    external_id CHAR(36) NOT NULL DEFAULT (UUID()),
    full_name VARCHAR(255) NOT NULL,
    phone_hash VARCHAR(64) NOT NULL,
    phone_encrypted BLOB NOT NULL,
    email_hash VARCHAR(64) DEFAULT NULL,
    email_encrypted BLOB DEFAULT NULL,
    city_id INT NOT NULL,
    national_id_hash VARCHAR(64) DEFAULT NULL,
    national_id_encrypted BLOB DEFAULT NULL,
    status ENUM('active','suspended','banned','pending_verification') NOT NULL DEFAULT 'pending_verification',
    rating DECIMAL(3,2) NOT NULL DEFAULT 5.00,
    total_rides INT NOT NULL DEFAULT 0,
    preferred_payment ENUM('cash','telebirr','cbe_birr','awash_pay','amole','card') NOT NULL DEFAULT 'cash',
    language_preference VARCHAR(10) NOT NULL DEFAULT 'am',
    last_known_lat DECIMAL(10,8) DEFAULT NULL,
    last_known_lon DECIMAL(11,8) DEFAULT NULL,
    last_location_updated DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    PRIMARY KEY (user_id),
    UNIQUE KEY uq_user_external (external_id),
    UNIQUE KEY uq_user_phone (phone_hash),
    CONSTRAINT fk_user_city FOREIGN KEY (city_id) REFERENCES cities(city_id),
    CONSTRAINT chk_user_rating CHECK (rating >= 1.0 AND rating <= 5.0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_phones (
    phone_id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    phone_hash VARCHAR(64) NOT NULL,
    phone_encrypted BLOB NOT NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    is_verified TINYINT(1) NOT NULL DEFAULT 0,
    verified_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (phone_id),
    CONSTRAINT fk_uphone_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS drivers (
    driver_id BIGINT NOT NULL AUTO_INCREMENT,
    external_id CHAR(36) NOT NULL DEFAULT (UUID()),
    full_name VARCHAR(255) NOT NULL,
    phone_hash VARCHAR(64) NOT NULL,
    phone_encrypted BLOB NOT NULL,
    license_number_hash VARCHAR(64) NOT NULL,
    license_number_encrypted BLOB NOT NULL,
    license_expiry DATE NOT NULL,
    city_id INT NOT NULL,
    vehicle_id BIGINT DEFAULT NULL,
    status ENUM('available','busy','offline','on_break') NOT NULL DEFAULT 'offline',
    current_lat DECIMAL(10,8) DEFAULT NULL,
    current_lon DECIMAL(11,8) DEFAULT NULL,
    heading_degrees SMALLINT DEFAULT NULL,
    speed_kmh DECIMAL(5,2) DEFAULT NULL,
    location_updated_at DATETIME DEFAULT NULL,
    rating DECIMAL(3,2) NOT NULL DEFAULT 5.00,
    total_rides INT NOT NULL DEFAULT 0,
    total_earnings DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    acceptance_rate DECIMAL(5,2) NOT NULL DEFAULT 100.00,
    cancellation_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    is_background_verified TINYINT(1) NOT NULL DEFAULT 0,
    background_verified_at DATETIME DEFAULT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    PRIMARY KEY (driver_id),
    UNIQUE KEY uq_driver_external (external_id),
    UNIQUE KEY uq_driver_phone (phone_hash),
    UNIQUE KEY uq_driver_license (license_number_hash),
    CONSTRAINT fk_driver_city FOREIGN KEY (city_id) REFERENCES cities(city_id),
    CONSTRAINT fk_driver_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id) ON DELETE SET NULL,
    CONSTRAINT chk_driver_rating CHECK (rating >= 1.0 AND rating <= 5.0)
) ENGINE=InnoDB;
